apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: s2eo5guwo-python 
  janus-idp.io/tekton: s2eo5guwo-python
  backstage.io/kubernetes-id: s2eo5guwo-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: s2eo5guwo-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml